# Generated by Django 3.2.13 on 2024-03-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInfos',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('place_description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mainImage', models.ImageField(default='defaults/defaultimg.jpg', upload_to='savedimages')),
                ('video', models.FileField(default='defaults/defaultvid.mp4', upload_to='savedvideos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carouselImage1', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage2', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage3', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage4', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage5', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage6', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage7', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage8', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage9', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage10', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('carouselImage11', models.ImageField(blank=True, upload_to='savedcarouselimages')),
                ('icon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapApp.icontype')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapApp.placetype')),
            ],
        ),
    ]
