# Generated by Django 3.2.13 on 2024-03-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeinfos',
            name='icon_type',
        ),
        migrations.AlterField(
            model_name='placeinfos',
            name='place_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='placeinfos',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='IconType',
        ),
    ]
